name: GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0    
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.83.1'
          extended: true
#      - name: tar-notes
#        run: tar czvf notes.tar.gz about/ algorithms/ devops/ kubernetes/ linux/ others/ && rm -rf .github .obsidian
        
      - name: Build-init 
        run: hugo new site wiki && cd wiki/ && git clone https://github.com/vinloong/hugo-theme-relearn.git themes/hugo-theme-relearn

      - name: pre-config
        run: mv _config/config.toml wiki/ && mv README.md wiki/content/_index.md
  
      - name: build
        run: cd wiki && hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          deploy_key: ${{ secrets.NOTES_DEPLOY_KEY }}
          publish_dir: ./wiki/public
